version: '3.8'

services:
  gameserver:
    build: .
    container_name: forgotten_server
    ports:
      - "7171:7171"
      - "7172:7172"
    volumes:
      - ./data:/data
    depends_on:
      - db
    networks:
      - forgotten_network

  webserver:
    image: php:7.4-apache
    container_name: forgotten_cms
    ports:
      - "80:80"
    volumes:
      - ./cms:/var/www/html
    depends_on:
      - db
    networks:
      - forgotten_network

  db:
    image: mysql:5.7
    container_name: forgotten_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: tfs
      MYSQL_USER: tfsuser
      MYSQL_PASSWORD: tfspassword
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - forgotten_network

volumes:
  db_data:

networks:
  forgotten_network:
